Imported Debian version 0.3.8-64+0m5

diff --git a/debian/event.d/system-services/rcS-late b/debian/event.d/system-services/rcS-late
--- a/debian/event.d/system-services/rcS-late
+++ b/debian/event.d/system-services/rcS-late
@@ -1,11 +1,19 @@
 description "late rcS actions"
 
-start on started xomap
-stop on stopping bme
+start on started hal
+stop on stopping hal
 
 console none
 
 script
+    ACT_DEAD=0
+    HOME_MOUNTED=0
+    
+    #check act_dead
+    if [ -e /tmp/ACT_DEAD ]; then
+      ACT_DEAD=1
+    fi
+
     # Generate fstab and mount /home
     . /etc/default/mount-opts
 
@@ -19,35 +27,65 @@ script
     cmp -s $tmp_fstab $fstab || cp $tmp_fstab $fstab
     rm -f $tmp_fstab
 
-    /bin/mount /home || echo "Failed to mount /home partition."
+    if [ $ACT_DEAD -eq 0 ]; then
+      /sbin/swapon -a || echo "Failed to enable paging partition."
+      # Setup lowmem module
+      echo 32768  > /proc/sys/vm/lowmem_deny_watermark_pages
+      echo 98304  > /proc/sys/vm/lowmem_notify_high_pages
+      echo 131072 > /proc/sys/vm/lowmem_notify_low_pages
+      echo 1024   > /proc/sys/vm/lowmem_nr_decay_pages
+      # Exclude some UIDs from memory allocation denial.
+      # 30000 is messagebus, 30001 could be used by Matchbox
+      echo "30000 30001 30002 30003" > /proc/sys/vm/lowmem_allowed_uids
+    fi
+
+    /bin/mount /home && HOME_MOUNTED=1
+    
+    if [ $ACT_DEAD -eq 0 ]
+    then
+      if [ -x /usr/sbin/maemo-optify-firstboot.sh ]; then
+          . /usr/sbin/maemo-optify-firstboot.sh
+      fi
+        
+      [ ! -d /opt ] && mkdir /opt
+      /bin/mount /opt || echo "Failed to mount(bind) /opt."
+      
+      if [ $HOME_MOUNTED -eq 1 ]
+      then
+        if [ -x /usr/sbin/maemo-optify-auto-opt.sh ]; then
+            . /usr/sbin/maemo-optify-auto-opt.sh
+        fi
+      fi
+      
+      if [ -d /home/preinstalled -a -d /home/user ]
+      then 
+        rm -rf /home/user
+      fi     
+    
+      if [ ! -d /home/user ]
+      then
+        if [ -d /home/preinstalled ]
+        then
+          mv /home/preinstalled /home/user
+        else
+          mkdir /home/user
+        fi
+        cd /etc/skel
+        cp -a . /home/user
+        chown -R user:users /home/user
+        sync
+      fi
+    fi
 
     if [ ! -d /home/user ]
     then
-      if [ -d /home/preinstalled ]
-      then
-        mv /home/preinstalled /home/user
-      else
-        mkdir /home/user
-      fi
-      cd /etc/skel
-      cp -a . /home/user
-      chown -R user:users /home/user
+      mkdir /home/user
+      chown user:users /home/user
+      sync
     fi
 
     # We can safely continue booting now.
     initctl emit MOUNTS_OK
-
-    /sbin/swapon -a || echo "Failed to enable paging partition."
-
-    # Setup lowmem module
-    echo 32768  > /proc/sys/vm/lowmem_deny_watermark_pages
-    echo 98304  > /proc/sys/vm/lowmem_notify_high_pages
-    echo 131072 > /proc/sys/vm/lowmem_notify_low_pages
-    echo 1024   > /proc/sys/vm/lowmem_nr_decay_pages
-
-    # Exclude some UIDs from memory allocation denial.
-    # 30000 is messagebus, 30001 could be used by Matchbox
-    echo "30000 30001 30002 30003" > /proc/sys/vm/lowmem_allowed_uids
 
     # Adjust flushing of memory card buffers
     echo 40 > /proc/sys/vm/dirty_ratio
