Imported Debian version 0.3.8-67+0m5

diff --git a/debian/event.d/system-services/rcS-late b/debian/event.d/system-services/rcS-late
--- a/debian/event.d/system-services/rcS-late
+++ b/debian/event.d/system-services/rcS-late
@@ -6,6 +6,27 @@ stop on stopping hal
 console none
 
 script
+    #mount /home; fix ext3 and retry mounting if 1st attempt fails
+    mount_home ()
+    {
+    /bin/mount /home && grep -q "/home ext3 rw" /proc/mounts
+    if [ $? -eq 0 ]
+    then
+      return 0
+    else
+      grep -q "/home ext3 ro" /proc/mounts
+      if [ $? -eq 0 ]
+      then
+        umount /home
+      fi
+      HOME_DEV=`grep "/home ext3" /etc/fstab | cut -d' ' -f1`
+      fsck.ext3 -y $HOME_DEV >> /var/lib/fsck_ext3_home.log 2>&1
+      sync
+      /bin/mount /home && grep -q "/home ext3 rw" /proc/mounts
+      return $?
+    fi
+    }
+
     ACT_DEAD=0
     HOME_MOUNTED=0
     
@@ -20,7 +41,7 @@ script
     fstab=/etc/fstab
     tmp_fstab=/tmp/fstab
 
-    sfdisk -l /dev/mmcblk0 | awk \
+    sfdisk -l /dev/mmcblk0 | /bin/busybox awk \
     	-v home_opts="$home_opts" -v fat_opts="$fat_opts" \
 	-f /usr/lib/genfstab.awk > $tmp_fstab
 
@@ -39,17 +60,33 @@ script
       echo "30000 30001 30002 30003" > /proc/sys/vm/lowmem_allowed_uids
     fi
 
-    /bin/mount /home && HOME_MOUNTED=1
-    
+    mount_home && HOME_MOUNTED=1
+   
+    # If failed to mount /home and system has been already optified - reboot 
+    if [ $HOME_MOUNTED -eq 0 ]
+    then
+      if [ -e /var/lib/maemo-optify-firstboot-do-not-clean-home-opt ]; then
+        telinit 6
+      fi
+    else
+      [ ! -d /home/opt ] && mkdir /home/opt
+      [ ! -d /opt ] && mkdir /opt
+    fi   
+ 
     if [ $ACT_DEAD -eq 0 ]
     then
-      if [ -x /usr/sbin/maemo-optify-firstboot.sh ]; then
-          . /usr/sbin/maemo-optify-firstboot.sh
+      if [ $HOME_MOUNTED -eq 1 ]
+      then
+        if [ -x /usr/sbin/maemo-optify-firstboot.sh ]; then
+            . /usr/sbin/maemo-optify-firstboot.sh
+        fi
       fi
-        
-      [ ! -d /opt ] && mkdir /opt
-      /bin/mount /opt || echo "Failed to mount(bind) /opt."
+    fi    
+    
+    /bin/mount /opt || echo "Failed to mount(bind) /opt."
       
+    if [ $ACT_DEAD -eq 0 ]
+    then
       if [ $HOME_MOUNTED -eq 1 ]
       then
         if [ -x /usr/sbin/maemo-optify-auto-opt.sh ]; then
